ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "isAdmin" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "apiAccessDisabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "importsWriteDisabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "templatesWriteDisabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "launchesDisabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "aiEnhancementsDisabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastSeenAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "sessionIssuedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "sessionExpiresAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "User_isAdmin_idx" ON "User"("isAdmin");
CREATE INDEX IF NOT EXISTS "User_sessionExpiresAt_idx" ON "User"("sessionExpiresAt");
